### ISSUE TITLE
Is your fork of the SmartMatrixServer required?

### ISSUE THREAD

**Issue by d0ugal** [drudge/esphome-smartmatrix#1]
Hi,

Wonderirng if this will work with the upstream version or not?

Thanks

**Comment by drudge** [comment]
I believe he's changed the messaging protocol in his server recently so I don't believe the two implementations are compatible any longer.

I'm actually working on a new Go version of the server that backs this firmware and embeds Pixlet, an MQTT broker, and a caching server into one binary.

**Comment by d0ugal** [comment]
Thanks. I tried yours but there isn’t a amd64 docker build so I’ll build one. Interested in seeing the Go version too - I’ll dig around.

**Comment by drudge** [comment]
Oh sorry about that, it was my intention to publish both arm and amd64 builds. I've updated the CI pipeline and published a new image that supports amd64.

**Comment by d0ugal** [comment]
Great, thanks!
